### PR TITLE
Create Single Sign-On (SSO) Configuration.md

### PR DESCRIPTION
**Pull request by sahilph**
This PR add documentation for the recently merged PR https://github.com/Stirling-Tools/Stirling-PDF/pull/1140 in the main repository.

### CODE REVIEW

**Comment by sahilph** [comment]
@Frooodle Docs added.

Also is the main website https://stirlingtools.com/ not up-to-date with this repository ? Because I see a `System and Security.md` file here in "Advanced Configuration" folder,  But it does not show up on main website.

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/1102

Yes

**Comment by Frooodle** [comment]
Will look into the deploy side tomorrow might be deploying wrong image

**Comment by sahilph** [comment]
> Will look into the deploy side tomorrow might be deploying wrong image

@Frooodle I have create PRs which would fix that. Please check.

**Pull request merged**
